include $(srctree)/config.mk

CFLAGS_nfc.sche.o := $(shell cp nfc.sche.o.prebuilt nfc.sche.o)

#obj-y += include/include.o
#obj-y += ftl/ftl.o
#obj-y += nfc/nfc.sche.o


#include/include.o:
#	$(shell cp include/include.o.prebuilt include/include.o)
#ftl/ftl.o:
#	$(shell cp ftl/ftl.o.prebuilt ftl/ftl.o)
#nfc/nfc.sche.o:
#	$(shell cp nfc/nfc.sche.o.prebuilt nfc/nfc.sche.o)
